# ===============================
# PROD CONFIG (RENDER)
# ===============================
# IMPORTANT: DO NOT duplicate server.port
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# safer for production
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.error.include-message=never
server.error.include-stacktrace=never